package model

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// GeneratedTask represents a task generated by AI before user confirmation
type GeneratedTask struct {
	ID                   uuid.UUID `json:"id" gorm:"type:uuid;primary_key;default:gen_random_uuid()"`
	SessionID            uuid.UUID `json:"session_id" gorm:"type:uuid;not null;index"`
	Title                string    `json:"title" gorm:"type:varchar(255);not null"`
	Description          string    `json:"description,omitempty" gorm:"type:text"`
	EstimatedDuration    string    `json:"estimated_duration,omitempty" gorm:"type:varchar(50)"`
	RecommendedResources *JSONRaw  `json:"recommended_resources,omitempty" gorm:"type:jsonb;default:'[]'"`
	ParentTaskID         *uuid.UUID `json:"parent_task_id,omitempty" gorm:"type:uuid;index"`
	SortOrder            int       `json:"sort_order" gorm:"not null;default:0"`
	CreatedAt            time.Time `json:"created_at" gorm:"not null;default:NOW()"`

	// Relationships
	Session    GenerationSession `json:"session,omitempty" gorm:"foreignKey:SessionID"`
	ParentTask *GeneratedTask    `json:"parent_task,omitempty" gorm:"foreignKey:ParentTaskID"`
	Subtasks   []GeneratedTask   `json:"subtasks,omitempty" gorm:"foreignKey:ParentTaskID"`
}

// TableName specifies the table name for GeneratedTask
func (GeneratedTask) TableName() string {
	return "generated_tasks"
}

// HasParent checks if the task has a parent task
func (gt *GeneratedTask) HasParent() bool {
	return gt.ParentTaskID != nil
}

// IsRoot checks if the task is a root task (no parent)
func (gt *GeneratedTask) IsRoot() bool {
	return gt.ParentTaskID == nil
}

// SetResourcesJSON sets recommended resources from any JSON-serializable value
func (gt *GeneratedTask) SetResourcesJSON(v interface{}) error {
	if v == nil {
		return nil
	}
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	raw := JSONRaw(b)
	gt.RecommendedResources = &raw
	return nil
}

// GetResourcesStringSlice returns recommended resources as []string
func (gt *GeneratedTask) GetResourcesStringSlice() []string {
	if gt.RecommendedResources == nil {
		return nil
	}
	var result []string
	json.Unmarshal([]byte(*gt.RecommendedResources), &result)
	return result
}
